export type CodexMethodDisposition = "mapped" | "extension" | "disabled";

export const CODEX_SERVER_REQUESTS = {
	"item/commandExecution/requestApproval": "mapped",
	"item/fileChange/requestApproval": "mapped",
	"item/tool/requestUserInput": "mapped",
	"mcpServer/elicitation/request": "mapped",
	"item/permissions/requestApproval": "mapped",
	"item/tool/call": "mapped",
	"account/chatgptAuthTokens/refresh": "extension",
	"attestation/generate": "disabled",
	applyPatchApproval: "disabled",
	execCommandApproval: "disabled",
} as const satisfies Record<string, CodexMethodDisposition>;

export const CODEX_SERVER_NOTIFICATIONS = {
	error: "mapped",
	"thread/started": "mapped",
	"thread/status/changed": "mapped",
	"thread/archived": "mapped",
	"thread/deleted": "mapped",
	"thread/unarchived": "mapped",
	"thread/closed": "mapped",
	"skills/changed": "mapped",
	"thread/name/updated": "mapped",
	"thread/goal/updated": "mapped",
	"thread/goal/cleared": "mapped",
	"thread/environment/connected": "extension",
	"thread/environment/disconnected": "extension",
	"thread/settings/updated": "extension",
	"thread/tokenUsage/updated": "mapped",
	"turn/started": "mapped",
	"hook/started": "mapped",
	"turn/completed": "mapped",
	"hook/completed": "mapped",
	"turn/diff/updated": "mapped",
	"turn/plan/updated": "mapped",
	"item/started": "mapped",
	"item/autoApprovalReview/started": "extension",
	"item/autoApprovalReview/completed": "extension",
	"item/completed": "mapped",
	"rawResponseItem/completed": "extension",
	"rawResponse/completed": "extension",
	"item/agentMessage/delta": "mapped",
	"item/plan/delta": "mapped",
	"command/exec/outputDelta": "extension",
	"process/outputDelta": "disabled",
	"process/exited": "disabled",
	"item/commandExecution/outputDelta": "mapped",
	"item/commandExecution/terminalInteraction": "extension",
	"item/fileChange/outputDelta": "disabled",
	"item/fileChange/patchUpdated": "mapped",
	"serverRequest/resolved": "mapped",
	"item/mcpToolCall/progress": "extension",
	"mcpServer/oauthLogin/completed": "mapped",
	"mcpServer/startupStatus/updated": "mapped",
	"account/updated": "mapped",
	"account/rateLimits/updated": "mapped",
	"app/list/updated": "mapped",
	"remoteControl/status/changed": "disabled",
	"externalAgentConfig/import/progress": "extension",
	"externalAgentConfig/import/completed": "extension",
	"fs/changed": "mapped",
	"item/reasoning/summaryTextDelta": "mapped",
	"item/reasoning/summaryPartAdded": "mapped",
	"item/reasoning/textDelta": "mapped",
	"thread/compacted": "mapped",
	"model/rerouted": "mapped",
	"model/verification": "mapped",
	"turn/moderationMetadata": "extension",
	"model/safetyBuffering/updated": "mapped",
	warning: "mapped",
	guardianWarning: "extension",
	deprecationNotice: "extension",
	configWarning: "mapped",
	"fuzzyFileSearch/sessionUpdated": "extension",
	"fuzzyFileSearch/sessionCompleted": "extension",
	"thread/realtime/started": "disabled",
	"thread/realtime/itemAdded": "disabled",
	"thread/realtime/transcript/delta": "disabled",
	"thread/realtime/transcript/done": "disabled",
	"thread/realtime/outputAudio/delta": "disabled",
	"thread/realtime/sdp": "disabled",
	"thread/realtime/error": "disabled",
	"thread/realtime/closed": "disabled",
	"windows/worldWritableWarning": "extension",
	"windowsSandbox/setupCompleted": "extension",
	"account/login/completed": "mapped",
} as const satisfies Record<string, CodexMethodDisposition>;

export const CODEX_DISPATCHED_CLIENT_REQUESTS = [
	"initialize",
	"thread/start",
	"thread/resume",
	"thread/fork",
	"thread/archive",
	"thread/delete",
	"thread/name/set",
	"thread/metadata/update",
	"thread/unarchive",
	"thread/compact/start",
	"thread/list",
	"thread/read",
	"skills/list",
	"hooks/list",
	"plugin/list",
	"app/list",
	"turn/start",
	"turn/steer",
	"turn/interrupt",
	"review/start",
	"model/list",
	"modelProvider/capabilities/read",
	"permissionProfile/list",
	"mcpServerStatus/list",
	"getAuthStatus",
] as const;

export function codexMethodDisposition(
	registry: Readonly<Record<string, CodexMethodDisposition>>,
	method: string,
): CodexMethodDisposition {
	const disposition = registry[method];
	if (!disposition) throw new Error(`Codex schema method is not locked: ${method}`);
	return disposition;
}
